### PR TITLE
fix(components/molecule/collapsible): fix text alignment

### LINKED ISSUE #1736: Collapsible DEMO - Alignments are not working
**Describe the bug**
Collapsible - Alignments are not working (at least in the Demo)

alignments ok

**Steps to reproduce**
1. Go to [Collapsible](https://sui-components.vercel.app/workbench/molecule/collapsible/demo)
2. Find the alignment demos
3. See the error, all of them are aligned to the left

**Expected behaviour**
Each of them should work

alignments not working

### PR DESCRIPTION
**Pull request by mslourens**
ISSUES CLOSED: #1736

## molecule/collapsible
**TASK**: #1736 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Only
- [ ] Refactor

### Description, Motivation and Context
the collapsible component has a alignContainer which just aligns the collapsible button container, not the text container. I changed the property name `alignContainer` to `alignContent` and set the class to the text of the collapsible.

### Screenshots - Animations
image

### CODE REVIEW

File: components/molecule/collapsible/src/index.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ const CONTENT_ALIGN = {
 const MoleculeCollapsible = ({
   onClose = () => {},
   onOpen = () => {},
-  alignContainer,
+  alignContent,
```
Comment (andresin87) [inline components/molecule/collapsible/src/index.js]: Thats a good point but unfortunately it will be a major change. Its better to maintain the prop name until de decide to create a major

**Review by andresin87 — CHANGES_REQUESTED** [review]

**Review by andresin87 — APPROVED** [review]
