### PR TITLE
fix(components/molecule/modal): Add a new prop to determine if the modal overflow is visible or not

### LINKED ISSUE #1515: Modal overflow when use dropdown select
**Describe the bug**
When a select dropdown is visible, modal scrolls

**Expected behaviour**
Captura de pantalla 2021-05-19 a las 11 12 30

**Screenshots**
Captura de pantalla 2021-05-19 a las 11 11 32

### PR DESCRIPTION
**Pull request by azaharamg**
## molecule/modal
**TASK**: https://github.com/SUI-Components/sui-components/issues/1515

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Only
- [ ] Refactor

### Description, Motivation and Context

When we include a component inside the modal component and its content is bigger than the modal itself, the modal is configured to add a vertical scroll.

Sometimes, for example when dropdown options are opened, we need that the modal doesn't show the scroll and the dropdown list should be opened over the modal content.

To solve it, I have added a new boolean prop `visibleOverflow`. When is `true`, components will be displayed over the modal otherwise a vertical scroll will be added if needed.

### Screenshots - Animations

image

### CODE REVIEW

**Review by beatrizip — APPROVED** [review]

File: components/molecule/modal/src/Content/index.js [hunk 1]
```diff
@@ -45,7 +47,8 @@ const MoleculeModalContent = ({
 MoleculeModalContent.propTypes = {
   className: PropTypes.string,
   enableContentScroll: PropTypes.bool,
-  withoutIndentation: PropTypes.bool
+  withoutIndentation: PropTypes.bool,
+  visibleOverflow: PropTypes.bool
```
Comment (andresin87) [inline components/molecule/modal/src/Content/index.js]: boolean prop --> isPrefix

`isOverflowVisible` name plz

File: components/molecule/modal/src/MoleculeModal.js [hunk 2]
```diff
@@ -127,7 +128,8 @@ const MoleculeModal = forwardRef(
       const dialogClassName = cx(suitClass({element: 'dialog'}), {
         [suitClass({element: 'dialog--out'})]: isClosing,
         [suitClass({element: 'dialog--fit'})]: fitContent,
-        [suitClass({element: `dialog--size-${size}`})]: !!size
+        [suitClass({element: `dialog--size-${size}`})]: !!size,
+        [suitClass({element: 'dialog--visible'})]: visibleOverflow
```
Comment (andresin87) [inline components/molecule/modal/src/MoleculeModal.js]: name it full semantical `dialog--overflowVisible`

File: components/molecule/modal/src/Content/index.js (hunk 1 above)
Comment (azaharamg) [reply components/molecule/modal/src/Content/index.js]: Thanks, done!

File: components/molecule/modal/src/MoleculeModal.js (hunk 2 above)
Comment (azaharamg) [reply components/molecule/modal/src/MoleculeModal.js]: Thanks, done!

File: components/molecule/modal/src/index.scss [hunk 3]
```diff
@@ -143,7 +143,7 @@ body.is-MoleculeModal-open {
       }
     }
 
-    &--visible {
+    &--overflowVisible {
```
Comment (andresin87) [inline components/molecule/modal/src/index.scss]: visible-overflow is the class you added b4

Comment (andresin87) [reply components/molecule/modal/src/index.scss]: [`${baseClassName}--visible-overflow`]:

Comment (azaharamg) [reply components/molecule/modal/src/index.scss]: Ups, sorry. I've fixed it

**Review by andresin87 — APPROVED** [review]

**Comment by turolopezsanabria** [comment]
👏🏼  thnkx!

**Comment by turolopezsanabria** [comment]
guay! @beatrizip I think you reported this one wayyy back in time, I'm so happy there's a solution now
